export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    logo: 'FutIA',
    assistant: 'AI Assistant',
    live: 'Live Matches',
    news: 'News',
    competitions: 'Competitions',
    transfers: 'Transfers',
    quiz: 'Quiz & Dictionary',
    account: 'My Account',
    searchPlaceholder: 'Search players, teams, matches...',
    favorites: 'Favorites',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    todaysMatches: "Today's Matches",
    featuredMatch: 'Featured Match',
    latestNews: 'Latest News',
    trendingPlayers: 'Trending Players',
    trendingTeams: 'Trending Teams',
    transferMarket: 'Transfer Market Tracker',
    predict: 'AI Match Prediction',
    summary: 'AI Match Summary',
    formations: 'Starting Formations',
    bench: 'Bench',
    timeline: 'Match Timeline',
    statistics: 'Statistics',
    headToHead: 'Head-to-Head',
    recentForm: 'Recent Form',
    possession: 'Possession',
    shots: 'Shots (On Target)',
    corners: 'Corners',
    fouls: 'Fouls',
    offside: 'Offside',
    expectedGoals: 'Expected Goals (xG)',
    squad: 'Squad',
    fixtures: 'Upcoming Fixtures',
    coach: 'Coach',
    stadium: 'Stadium',
    founded: 'Founded',
    country: 'Country',
    goals: 'Goals',
    assists: 'Assists',
    cleanSheets: 'Clean Sheets',
    marketValue: 'Market Value',
    biography: 'Biography',
    careerHistory: 'Career History',
    confirmedTransfers: 'Confirmed Transfers',
    rumours: 'Transfer Rumours',
    freeAgents: 'Free Agents',
    loans: 'Loans',
    topScorers: 'Top Scorers',
    topAssists: 'Top Assists',
    notifications: 'Notifications',
    saveFavorites: 'Save Favorites',
    installApp: 'Install FutIA App',
    factsTitle: 'Daily Football Fact',
    dictionaryTitle: 'Football Dictionary',
    aboutUs: 'About FutIA',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie Policy',
    contactUs: 'Contact Us',
    disclaimer: 'Disclaimer'
  },
  pt: {
    logo: 'FutIA',
    assistant: 'Assistente IA',
    live: 'Jogos ao Vivo',
    news: 'Notícias',
    competitions: 'Competições',
    transfers: 'Transferências',
    quiz: 'Quiz e Dicionário',
    account: 'Minha Conta',
    searchPlaceholder: 'Buscar jogadores, times, partidas...',
    favorites: 'Favoritos',
    settings: 'Configurações',
    theme: 'Tema',
    language: 'Idioma',
    todaysMatches: 'Jogos de Hoje',
    featuredMatch: 'Jogo em Destaque',
    latestNews: 'Últimas Notícias',
    trendingPlayers: 'Jogadores em Alta',
    trendingTeams: 'Times em Alta',
    transferMarket: 'Mercado de Transferências',
    predict: 'Previsão da IA',
    summary: 'Resumo da IA',
    formations: 'Escalações Iniciais',
    bench: 'Banco de Reservas',
    timeline: 'Linha do Tempo',
    statistics: 'Estatísticas',
    headToHead: 'Confronto Direto',
    recentForm: 'Forma Recente',
    possession: 'Posse de Bola',
    shots: 'Chutes (No Alvo)',
    corners: 'Escanteios',
    fouls: 'Faltas',
    offside: 'Impedimento',
    expectedGoals: 'Gols Esperados (xG)',
    squad: 'Elenco',
    fixtures: 'Próximos Jogos',
    coach: 'Treinador',
    stadium: 'Estádio',
    founded: 'Fundado',
    country: 'País',
    goals: 'Gols',
    assists: 'Assistências',
    cleanSheets: 'Jogos sem Sofrer Gols',
    marketValue: 'Valor de Mercado',
    biography: 'Biografia',
    careerHistory: 'Histórico de Carreira',
    confirmedTransfers: 'Transferências Confirmadas',
    rumours: 'Rumores do Mercado',
    freeAgents: 'Agentes Livres',
    loans: 'Empréstimos',
    topScorers: 'Artilheiros',
    topAssists: 'Líderes de Assistência',
    notifications: 'Notificações',
    saveFavorites: 'Salvar Favoritos',
    installApp: 'Instalar Aplicativo',
    factsTitle: 'Fato de Futebol do Dia',
    dictionaryTitle: 'Dicionário de Futebol',
    aboutUs: 'Sobre Nós',
    privacyPolicy: 'Política de Privacidade',
    termsOfService: 'Termos de Serviço',
    cookiePolicy: 'Política de Cookies',
    contactUs: 'Fale Conosco',
    disclaimer: 'Aviso Legal'
  },
  es: {
    logo: 'FutIA',
    assistant: 'Asistente IA',
    live: 'Partidos en Vivo',
    news: 'Noticias',
    competitions: 'Competiciones',
    transfers: 'Fichajes',
    quiz: 'Trivia y Diccionario',
    account: 'Mi Cuenta',
    searchPlaceholder: 'Buscar jugadores, equipos, partidos...',
    favorites: 'Favoritos',
    settings: 'Ajustes',
    theme: 'Tema',
    language: 'Idioma',
    todaysMatches: 'Partidos de Hoy',
    featuredMatch: 'Partido Destacado',
    latestNews: 'Últimas Noticias',
    trendingPlayers: 'Jugadores de Tendencia',
    trendingTeams: 'Equipos de Tendencia',
    transferMarket: 'Mercado de Fichajes',
    predict: 'Predicción IA',
    summary: 'Resumen IA',
    formations: 'Alineaciones Iniciales',
    bench: 'Banquillo',
    timeline: 'Línea de Tiempo',
    statistics: 'Estadísticas',
    headToHead: 'Cara a Cara',
    recentForm: 'Forma Reciente',
    possession: 'Posesión',
    shots: 'Disparos (Al Arco)',
    corners: 'Córneres',
    fouls: 'Faltas',
    offside: 'Fuera de Juego',
    expectedGoals: 'Goles Esperados (xG)',
    squad: 'Plantilla',
    fixtures: 'Próximos Partidos',
    coach: 'Entrenador',
    stadium: 'Estadio',
    founded: 'Fundado',
    country: 'País',
    goals: 'Goles',
    assists: 'Asistencias',
    cleanSheets: 'Porterías a Cero',
    marketValue: 'Valor de Mercado',
    biography: 'Biografía',
    careerHistory: 'Historial de Carrera',
    confirmedTransfers: 'Fichajes Confirmados',
    rumours: 'Rumores de Fichajes',
    freeAgents: 'Agentes Libres',
    loans: 'Préstamos',
    topScorers: 'Máximos Goleadores',
    topAssists: 'Asistencias',
    notifications: 'Notificaciones',
    saveFavorites: 'Guardar Favoritos',
    installApp: 'Instalar Aplicación',
    factsTitle: 'Dato de Fútbol del Día',
    dictionaryTitle: 'Diccionario de Fútbol',
    aboutUs: 'Sobre Nosotros',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    cookiePolicy: 'Política de Cookies',
    contactUs: 'Contáctenos',
    disclaimer: 'Aviso de Responsabilidad'
  },
  fr: {
    logo: 'FutIA',
    assistant: 'Assistant IA',
    live: 'Matchs en Direct',
    news: 'Actualités',
    competitions: 'Compétitions',
    transfers: 'Transferts',
    quiz: 'Quiz & Dictionnaire',
    account: 'Mon Compte',
    searchPlaceholder: 'Rechercher des joueurs, équipes, matchs...',
    favorites: 'Favoris',
    settings: 'Paramètres',
    theme: 'Thème',
    language: 'Langue',
    todaysMatches: "Matchs d'Aujourd'hui",
    featuredMatch: 'Match Vedette',
    latestNews: 'Dernières Infos',
    trendingPlayers: 'Joueurs Tendance',
    trendingTeams: 'Équipes Tendances',
    transferMarket: 'Marché des Transferts',
    predict: 'Prédiction IA',
    summary: 'Résumé IA',
    formations: 'Compositions Initiales',
    bench: 'Remplaçants',
    timeline: 'Chronologie',
    statistics: 'Statistiques',
    headToHead: 'Face-à-Face',
    recentForm: 'Forme Récente',
    possession: 'Possession',
    shots: 'Tirs (Cadrés)',
    corners: 'Corners',
    fouls: 'Fautes',
    offside: 'Hors-jeu',
    expectedGoals: 'Buts Attendus (xG)',
    squad: 'Effectif',
    fixtures: 'Matchs à Venir',
    coach: 'Entraîneur',
    stadium: 'Stade',
    founded: 'Fondé en',
    country: 'Pays',
    goals: 'Buts',
    assists: 'Passes Décisives',
    cleanSheets: 'Clean Sheets',
    marketValue: 'Valeur de Marché',
    biography: 'Biographie',
    careerHistory: 'Parcours Professionnel',
    confirmedTransfers: 'Transferts Confirmés',
    rumours: 'Rumeurs de Transfert',
    freeAgents: 'Agents Libres',
    loans: 'Prêts',
    topScorers: 'Meilleurs Buteurs',
    topAssists: 'Passeurs',
    notifications: 'Notifications',
    saveFavorites: 'Enregistrer les Favoris',
    installApp: "Installer l'Application",
    factsTitle: 'Anecdote de Football',
    dictionaryTitle: 'Lexique du Football',
    aboutUs: 'À Propos',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: "Conditions d'Utilisation",
    cookiePolicy: 'Politique de Cookies',
    contactUs: 'Contactez-nous',
    disclaimer: 'Mentions Légales'
  },
  de: {
    logo: 'FutIA',
    assistant: 'KI-Assistent',
    live: 'Live-Spiele',
    news: 'Nachrichten',
    competitions: 'Wettbewerbe',
    transfers: 'Transfers',
    quiz: 'Quiz & Lexikon',
    account: 'Mein Konto',
    searchPlaceholder: 'Spieler, Teams, Spiele suchen...',
    favorites: 'Favoriten',
    settings: 'Einstellungen',
    theme: 'Design',
    language: 'Sprache',
    todaysMatches: 'Heutige Spiele',
    featuredMatch: 'Top-Spiel',
    latestNews: 'Aktuelle News',
    trendingPlayers: 'Beliebte Spieler',
    trendingTeams: 'Beliebte Teams',
    transferMarket: 'Transfermarkt',
    predict: 'KI-Prognose',
    summary: 'KI-Spielbericht',
    formations: 'Aufstellungen',
    bench: 'Ersatzbank',
    timeline: 'Spielverlauf',
    statistics: 'Statistiken',
    headToHead: 'Direkter Vergleich',
    recentForm: 'Formkurve',
    possession: 'Ballbesitz',
    shots: 'Torschüsse (Aufs Tor)',
    corners: 'Ecken',
    fouls: 'Fouls',
    offside: 'Abseits',
    expectedGoals: 'Expected Goals (xG)',
    squad: 'Kader',
    fixtures: 'Kommende Spiele',
    coach: 'Trainer',
    stadium: 'Stadion',
    founded: 'Gegründet',
    country: 'Land',
    goals: 'Tore',
    assists: 'Vorlagen',
    cleanSheets: 'Weiße Weste',
    marketValue: 'Marktwert',
    biography: 'Biografie',
    careerHistory: 'Karriereverlauf',
    confirmedTransfers: 'Bestätigte Transfers',
    rumours: 'Transfergerüchte',
    freeAgents: 'Vereinslose Spieler',
    loans: 'Leihen',
    topScorers: 'Torschützen',
    topAssists: 'Vorlagengeber',
    notifications: 'Benachrichtigungen',
    saveFavorites: 'Favoriten speichern',
    installApp: 'App installieren',
    factsTitle: 'Fußball-Fakt des Tages',
    dictionaryTitle: 'Fußball-Lexikon',
    aboutUs: 'Über uns',
    privacyPolicy: 'Datenschutzerklärung',
    termsOfService: 'Nutzungsbedingungen',
    cookiePolicy: 'Cookie-Richtlinie',
    contactUs: 'Kontakt',
    disclaimer: 'Haftungsausschluss'
  },
  it: {
    logo: 'FutIA',
    assistant: 'Assistente IA',
    live: 'Partite in Diretta',
    news: 'Notizie',
    competitions: 'Competizioni',
    transfers: 'Calciomercato',
    quiz: 'Quiz & Dizionario',
    account: 'Mio Account',
    searchPlaceholder: 'Cerca giocatori, squadre, partite...',
    favorites: 'Preferiti',
    settings: 'Impostazioni',
    theme: 'Tema',
    language: 'Lingua',
    todaysMatches: 'Partite di Oggi',
    featuredMatch: 'Partita di Cartello',
    latestNews: 'Ultime Notizie',
    trendingPlayers: 'Giocatori del Momento',
    trendingTeams: 'Squadre del Momento',
    transferMarket: 'Mercato Trasferimenti',
    predict: 'Pronostico IA',
    summary: 'Sintesi IA',
    formations: 'Formazioni Ufficiali',
    bench: 'Panchina',
    timeline: 'Cronologia Partita',
    statistics: 'Statistiche',
    headToHead: 'Scontri Diretti',
    recentForm: 'Forma Recente',
    possession: 'Possesso Palla',
    shots: 'Tiri (In Porta)',
    corners: 'Calci d\'Angolo',
    fouls: 'Falli',
    offside: 'Fuorigioco',
    expectedGoals: 'Gol Previsti (xG)',
    squad: 'Rosa',
    fixtures: 'Prossimi Turni',
    coach: 'Allenatore',
    stadium: 'Stadio',
    founded: 'Fondato nel',
    country: 'Nazione',
    goals: 'Gol',
    assists: 'Assist',
    cleanSheets: 'Porte Intentate',
    marketValue: 'Valore di Mercato',
    biography: 'Biografia',
    careerHistory: 'Carriera',
    confirmedTransfers: 'Trasferimenti Ufficiali',
    rumours: 'Voci di Mercato',
    freeAgents: 'Svincolati',
    loans: 'Prestiti',
    topScorers: 'Capocannonieri',
    topAssists: 'Assist-man',
    notifications: 'Notifiche',
    saveFavorites: 'Salva Preferiti',
    installApp: 'Installa Applicazione',
    factsTitle: 'Pillola del Giorno',
    dictionaryTitle: 'Dizionario del Calcio',
    aboutUs: 'Chi Siamo',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Termini di Servizio',
    cookiePolicy: 'Cookie Policy',
    contactUs: 'Contattaci',
    disclaimer: 'Avvertenze'
  },
  ar: {
    logo: 'FutIA',
    assistant: 'مساعد الذكاء الاصطناعي',
    live: 'المباريات المباشرة',
    news: 'الأخبار',
    competitions: 'البطولات',
    transfers: 'الانتقالات',
    quiz: 'الاختبار والقاموس',
    account: 'حسابي',
    searchPlaceholder: 'ابحث عن لاعبين، فرق، مباريات...',
    favorites: 'المفضلة',
    settings: 'الإعدادات',
    theme: 'المظهر',
    language: 'اللغة',
    todaysMatches: 'مباريات اليوم',
    featuredMatch: 'المباراة البارزة',
    latestNews: 'آخر الأخبار',
    trendingPlayers: 'اللاعبون الأكثر تداولاً',
    trendingTeams: 'الفرق الأكثر تداولاً',
    transferMarket: 'سوق الانتقالات',
    predict: 'توقعات الذكاء الاصطناعي',
    summary: 'ملخص الذكاء الاصطناعي',
    formations: 'التشكيلة الأساسية',
    bench: 'دكة البدلاء',
    timeline: 'أحداث المباراة',
    statistics: 'الإحصائيات',
    headToHead: 'المواجهات المباشرة',
    recentForm: 'النتائج الأخيرة',
    possession: 'الاستحواذ',
    shots: 'التسديدات (على المرمى)',
    corners: 'الضربات الركنية',
    fouls: 'الأخطاء',
    offside: 'التسلل',
    expectedGoals: 'الأهداف المتوقعة (xG)',
    squad: 'قائمة الفريق',
    fixtures: 'المباريات القادمة',
    coach: 'المدرب',
    stadium: 'الملعب',
    founded: 'تأسس عام',
    country: 'البلد',
    goals: 'الأهداف',
    assists: 'التمريرات الحاسمة',
    cleanSheets: 'شباك نظيفة',
    marketValue: 'القيمة السوقية',
    biography: 'السيرة الذاتية',
    careerHistory: 'تاريخ المسيرة',
    confirmedTransfers: 'الانتقالات المؤكدة',
    rumours: 'شائعات الانتقالات',
    freeAgents: 'لاعبون أحرار',
    loans: 'إعارات',
    topScorers: 'الهدافون',
    topAssists: 'صناع اللعب',
    notifications: 'الإشعارات',
    saveFavorites: 'حفظ المفضلة',
    installApp: 'تثبيت التطبيق',
    factsTitle: 'حقيقة اليوم الكروية',
    dictionaryTitle: 'قاموس كرة القدم',
    aboutUs: 'معلومات عنا',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    cookiePolicy: 'سياسة ملفات الارتباط',
    contactUs: 'اتصل بنا',
    disclaimer: 'إخلاء المسؤولية'
  },
  ja: {
    logo: 'FutIA',
    assistant: 'AIアシスタント',
    live: 'ライブマッチ',
    news: 'ニュース',
    competitions: 'リーグ・大会',
    transfers: '移籍情報',
    quiz: 'クイズと辞書',
    account: 'マイアカウント',
    searchPlaceholder: '選手、チーム、試合を検索...',
    favorites: 'お気に入り',
    settings: '設定',
    theme: 'テーマ',
    language: '言語',
    todaysMatches: '本日の試合',
    featuredMatch: '注目の一戦',
    latestNews: '最新ニュース',
    trendingPlayers: '注目選手',
    trendingTeams: '注目チーム',
    transferMarket: '移籍マーケット',
    predict: 'AI勝敗予想',
    summary: 'AIマッチ要約',
    formations: 'スタメン編成',
    bench: 'ベンチメンバー',
    timeline: 'タイムライン',
    statistics: '統計データ',
    headToHead: '直接対決',
    recentForm: '最近の調子',
    possession: 'ボール支配率',
    shots: 'シュート (枠内)',
    corners: 'コーナーキック',
    fouls: 'ファウル',
    offside: 'オフサイド',
    expectedGoals: 'ゴール期待値 (xG)',
    squad: '選手一覧',
    fixtures: '今後の試合日程',
    coach: '監督',
    stadium: 'スタジアム',
    founded: '創立年',
    country: '国',
    goals: '得点数',
    assists: 'アシスト数',
    cleanSheets: '無失点試合',
    marketValue: '市場価値',
    biography: '経歴・プロフィール',
    careerHistory: 'キャリア履歴',
    confirmedTransfers: '確定した移籍',
    rumours: '移籍の噂',
    freeAgents: 'フリーエージェント',
    loans: '期限付き移籍',
    topScorers: '得点ランキング',
    topAssists: 'アシストランキング',
    notifications: '通知設定',
    saveFavorites: 'お気に入りを保存',
    installApp: 'アプリをインストール',
    factsTitle: '今日のサッカー豆知識',
    dictionaryTitle: 'サッカー専門用語集',
    aboutUs: '運営元について',
    privacyPolicy: 'プライバシーポリシー',
    termsOfService: '利用規約',
    cookiePolicy: 'クッキーポリシー',
    contactUs: 'お問い合わせ',
    disclaimer: '免責事項'
  },
  zh: {
    logo: 'FutIA',
    assistant: 'AI 足球助手',
    live: '实时比赛',
    news: '最新资讯',
    competitions: '赛事联赛',
    transfers: '转会市场',
    quiz: '答题与词典',
    account: '个人账户',
    searchPlaceholder: '搜索球员、球队、比赛...',
    favorites: '我的收藏',
    settings: '系统设置',
    theme: '色彩主题',
    language: '显示语言',
    todaysMatches: '今日赛程',
    featuredMatch: '焦点大战',
    latestNews: '头条新闻',
    trendingPlayers: '热门球员',
    trendingTeams: '人气球队',
    transferMarket: '转会追踪器',
    predict: 'AI 赛前预测',
    summary: 'AI 战报总结',
    formations: '首发阵容',
    bench: '替补席',
    timeline: '比赛事件轴',
    statistics: '数据统计',
    headToHead: '历史交锋',
    recentForm: '近期战绩',
    possession: '控球率',
    shots: '射门 (射正)',
    corners: '角球',
    fouls: '犯规',
    offside: '越位',
    expectedGoals: '预期进球数 (xG)',
    squad: '球队阵容',
    fixtures: '未来赛程',
    coach: '主教练',
    stadium: '主场球场',
    founded: '成立年份',
    country: '国家/地区',
    goals: '进球',
    assists: '助攻',
    cleanSheets: '零封对手',
    marketValue: '德转身价',
    biography: '个人简介',
    careerHistory: '职业生涯',
    confirmedTransfers: '官方转会',
    rumours: '转会传闻',
    freeAgents: '自由球员',
    loans: '租借形式',
    topScorers: '射手榜',
    topAssists: '助攻榜',
    notifications: '推送通知',
    saveFavorites: '保存收藏',
    installApp: '安装应用程序',
    factsTitle: '每日足球小知识',
    dictionaryTitle: '足球战术词典',
    aboutUs: '关于我们',
    privacyPolicy: '隐私政策',
    termsOfService: '服务条款',
    cookiePolicy: 'Cookie 政策',
    contactUs: '联系我们',
    disclaimer: '免责声明'
  },
  ko: {
    logo: 'FutIA',
    assistant: 'AI 비서',
    live: '라이브 경기',
    news: '축구 뉴스',
    competitions: '대회 및 리그',
    transfers: '이적 시장',
    quiz: '퀴즈 & 용어사전',
    account: '내 계정',
    searchPlaceholder: '선수, 팀, 경기 검색...',
    favorites: '즐겨찾기',
    settings: '설정',
    theme: '테마',
    language: '언어',
    todaysMatches: '오늘의 경기',
    featuredMatch: '주목할 경기',
    latestNews: '최신 뉴스',
    trendingPlayers: '트렌딩 선수',
    trendingTeams: '인기 구단',
    transferMarket: '이적시장 요약',
    predict: 'AI 경기 분석 및 예측',
    summary: 'AI 战报 요약',
    formations: '선발 라인업',
    bench: '교체 명단',
    timeline: '경기 시간대별 기록',
    statistics: '팀 통계',
    headToHead: '상대 전적',
    recentForm: '최근 전적',
    possession: '점유율',
    shots: '슈팅 (유효 슈팅)',
    corners: '코너킥',
    fouls: '파울',
    offside: '오프사이드',
    expectedGoals: '득점 기대치 (xG)',
    squad: '스쿼드',
    fixtures: '경기 일정',
    coach: '감독',
    stadium: '경기장',
    founded: '창단 연도',
    country: '국가',
    goals: '득점',
    assists: '도움',
    cleanSheets: '무실점 경기',
    marketValue: '시장 가치',
    biography: '바이오그래피',
    careerHistory: '선수 경력',
    confirmedTransfers: '오피셜 이적',
    rumours: '이적 루머',
    freeAgents: '자유 계약 (FA)',
    loans: '임대 이적',
    topScorers: '득점 순위',
    topAssists: '도움 순위',
    notifications: '알림 설정',
    saveFavorites: '즐겨찾기 저장',
    installApp: '앱 설치하기',
    factsTitle: '오늘의 축구 상식',
    dictionaryTitle: '축구 전문 용어 사전',
    aboutUs: '회사 소개',
    privacyPolicy: '개인정보 처리방침',
    termsOfService: '이용 약관',
    cookiePolicy: '쿠키 사용 정책',
    contactUs: '고객 센터',
    disclaimer: '면책 조항'
  }
};

export function getDeviceLanguage(): string {
  if (typeof navigator === 'undefined') return 'en';
  const lang = navigator.language.split('-')[0].toLowerCase();
  return TRANSLATIONS[lang] ? lang : 'en';
}
